/* soapClient.c
   Generated by gSOAP 2.8.9 from hello.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.9 2012-07-23 13:59:43 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__hello *ns2__hello, struct _ns2__helloResponse *ns2__helloResponse)
{	struct __ns1__hello soap_tmp___ns1__hello;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:80";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__hello.ns2__hello = ns2__hello;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__hello(soap, &soap_tmp___ns1__hello);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__hello(soap, &soap_tmp___ns1__hello, "-ns1:hello", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__hello(soap, &soap_tmp___ns1__hello, "-ns1:hello", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__helloResponse)
		return soap_closesock(soap);
	soap_default__ns2__helloResponse(soap, ns2__helloResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__helloResponse(soap, ns2__helloResponse, "ns2:helloResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
